### ISSUE TITLE
wrong screenshot if we push a tableviewcontroller

### ISSUE THREAD

**Issue by onishinji** [MarcoSero/MSSlideNavigationController#3] opened 2013-06-15 21:14 UTC
Hi, 

First, thank for your work, it's almost perfect :)

The bug: 
-  add a tableviewcontroller on your storyboard (empty)
-  create un button on viewcontrolerA
- add a triggered segue to the tableviewcontroller to push it.

Now, when we are on tableviewoncoller, go back slowy. The screenshot for the viewControllerA is wrong, it's a black screen (or white in my project). 

If you have an idea to resolve it, you work will became perfect :)

(ps: sorry for my bad english)

**Comment by MarcoSero** [comment] 2013-06-16 09:53
Thanks for reporting. Duplicate of this https://github.com/MarcoSero/MSSlideNavigationController/issues/2

**Closed as completed** 2013-06-16 09:52 UTC
Labels: duplicate
